version: '3'   
services:
  frontend_gpt:
    build: frontend_gpt
    
    ports:
      - 4500:4500
  
    stdin_open: true
    container_name: frontend_gpt
    restart: always  
    volumes:
      - ./frontend_gpt:/app
      - /app/node_modules
    depends_on:
      -  backend_gpt

  backend_gpt:
    build: backend_gpt
    ports:
       - 3005:3005
    
    container_name: backend_gpt
    restart: always  
    volumes:
      - ./backend_gpt:/app
      - /app/node_modules
 